In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 500)

In [2]:
data = pd.read_csv(r'C:\Users\zelja\Desktop\Masinsko ucenje\NoviProjekatDZ\carvana_final.csv')
#ucitavamo pripremljeni dataset u varijablu data

In [3]:
data.head(10)

VehicleAge    VehOdo    VNZIP1  VehBCost  IsOnlineSale  WarrantyCost  \
0   -0.106505  0.157568 -0.930981 -1.065435     -0.166793      0.194455   
1    0.475038 -0.401661 -0.930981 -1.523737     -0.166793     -1.075463   
2   -0.106505 -0.145604 -0.930981 -1.581025     -0.166793     -0.422936   
3    0.475038  0.652406 -0.930981 -0.664420     -0.166793     -1.135696   
4    0.475038  0.319123 -0.930981  1.168791     -0.166793     -0.590250   
5   -0.688048 -2.437894 -0.930981 -0.492556     -0.166793     -1.356551   
6   -0.106505  0.066890 -0.930981 -1.237298     -0.166793     -1.177525   
7    0.475038  0.577501 -0.930981  0.538625     -0.166793      0.194455   
8    0.475038  1.038062 -0.930981  1.913533     -0.166793     -0.702351   
9    1.056581  0.172522 -0.930981  1.970821     -0.166793     -0.590250   

   PurchYear  AcquisitionAuctionRatio  AcquisitionRetailRatio  \
0  -1.031687                -2.234466               -0.625095   
1  -1.031687                -1.699265               -0.670383   
2  -1.031687                -0.680499                0.648377   
3  -1.031687                -0.365471               -1.379759   
4  -1.031687                -0.350520               -0.373017   
5   0.969286                 0.555759                1.206192   
6   0.969286                -0.792041               -0.899194   
7   0.969286                -0.674444               -0.091268   
8   0.969286                -0.801313               -0.995639   
9   0.969286                 0.011925                0.410303   

   CurrentAuctionRatio  CurrentRetailRatio  Make_ACURA  Make_BUICK  \
0            -1.407804           -0.679097         0.0         0.0   
1            -1.860623           -1.232409         0.0         0.0   
2            -1.182456           -0.080270         0.0         0.0   
3            -0.136272            0.122553         0.0         0.0   
4            -0.241899            0.597293         0.0         0.0   
5             0.672741            0.249500         0.0         0.0   
6             0.143282           -0.582528         0.0         0.0   
7             1.367437            1.874114         0.0         0.0   
8            -0.737769           -0.943362         0.0         0.0   
9             0.789847            0.598396         0.0         0.0   

   Make_CADILLAC  Make_CHEVROLET  Make_CHRYSLER  Make_DODGE  Make_FORD  \
0            0.0             0.0            0.0         1.0        0.0   
1            0.0             0.0            0.0         1.0        0.0   
2            0.0             0.0            0.0         0.0        1.0   
3            0.0             0.0            0.0         0.0        0.0   
4            0.0             0.0            0.0         1.0        0.0   
5            0.0             0.0            0.0         0.0        0.0   
6            0.0             0.0            0.0         0.0        0.0   
7            0.0             0.0            0.0         1.0        0.0   
8            0.0             0.0            0.0         0.0        1.0   
9            0.0             0.0            0.0         1.0        0.0   

   Make_GMC  Make_HONDA  Make_HUMMER  Make_HYUNDAI  Make_INFINITI  Make_ISUZU  \
0       0.0         0.0          0.0           0.0            0.0         0.0   
1       0.0         0.0          0.0           0.0            0.0         0.0   
2       0.0         0.0          0.0           0.0            0.0         0.0   
3       0.0         0.0          0.0           0.0            0.0         0.0   
4       0.0         0.0          0.0           0.0            0.0         0.0   
5       0.0         0.0          0.0           0.0            0.0         0.0   
6       0.0         0.0          0.0           0.0            0.0         0.0   
7       0.0         0.0          0.0           0.0            0.0         0.0   
8       0.0         0.0          0.0           0.0            0.0         0.0   
9       0.0         0.0          0.0           0.0            0.0

In [60]:
data["IsBadBuy"].value_counts()
#Vidimo znacajan disbalans izmedju pozitivne klase, (IsBadBuy - Yes, 1), i negativne klase (IsBadBuy- No, 0)
#Gde je negativna klasa skoro sedam puta brojnija

0    5932
1     866
Name: IsBadBuy, dtype: int64

In [4]:
#Odvajamo izlaznu varijablu IsBadBuy i smestamo je u varijablu Y, ostale atribute smestamo u varijablu X
X = data.drop("IsBadBuy", axis = 1)
Y = data['IsBadBuy']

In [5]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, roc_auc_score


#pravimo funkciju evaluateMetrics koja ce racunati accuracy, precision, recall i f1 statistiku u zavisnosti od izlazne varijable y 
#koju vec poznajemo i y_pred koje cemo dobiti predvidjanjem iz nekog modela
def evaluate_metrics(Y, Y_pred):
    print(f'Accuracy : {accuracy_score(Y, Y_pred)}')
    print(f'Precision : {precision_score(Y, Y_pred)}')
    print(f'Recall : {recall_score(Y, Y_pred)}')
    print(f'F1 : {f1_score(Y, Y_pred)}')

In [6]:
#delimo dataset na train i test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [ ]:
#Zbog nan i inf vrednosti koristimo privremeno resenje, kako bismo mogle da pravimo modele

In [10]:
X_train = X_train.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
X_test = X_test.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
#posto nam je izbacivao ovu gresku Input contains NaN, infinity or a value too large for dtype('float64').
#nakon sredjivanja podataka, pronadjeno je resenje da se inf i nan vrednost zamene 0, svesno unosimo gresku u train set podataka

In [62]:
Y_test.value_counts()

0    1788
1     252
Name: IsBadBuy, dtype: int64

# Ispitujemo optimalne vrednosti hiperparametara za modele
Modeli:
- Stablo odlučivanja
- Knn
- Stacking
- Bagging

In [49]:
#Ispitujemo različitu kombinaciju parametara za stablo odlučivanja, pomoću gridsearchcv metode
#Ispitivacemo max_features tj optimalni broj atributa (iz dataseta), koje nas model treba da koristi
#Min_samples_leaf, tj najmanji broj listova koji treba da se nadje na kraju svake grane
#Max_depth, maksimalnu dubinu stabla
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [50]:
tree_params = {'max_features': [3,4,5,7,10,15,17,20,23,26,30], 'min_samples_leaf': [10,15,18,20,25,28,30], 'max_depth': [10,12,15,17,20]}
tree_grid = GridSearchCV(DecisionTreeClassifier(), parameters, cv = 5, scoring='roc_auc')

tree_grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [10, 12, 15, 17, 20],
                         'max_features': [3, 4, 5, 7, 10, 15, 17, 20, 23, 26,
                                          30],
                         'min_samples_leaf': [10, 15, 18, 20, 25, 28, 30]},
             scoring='roc_auc')

In [39]:
#Pristupamo najboljim parametrima koje je metoda odredila
tree_grid.best_params_

{'max_depth': 10, 'max_features': 20, 'min_samples_leaf': 28}

In [51]:
#Sada pomocu dobijenih parametara pravimo novi model stabla odlucivanja
#Pomocu best_estimator, koji predstavlja jednu instancu naseg modela,
#u ovom slucaju drvo odlucivanja, napravicemo model sa najoptimalnijim parametrima koje smo dobili pomocu gridSearcha
tree1 = tree_grid.best_estimator_
tree1.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=12, max_features=5, min_samples_leaf=25)

In [52]:
from sklearn.model_selection import cross_val_score

In [53]:
#koristimo 10tostruku kors validaciju za proveru koliko je model dobar
# kada prodjemo kobinaciju 10 foldova nad x i y train podacimam izracunacemo srednju gresku koja je napravljena
#kros validacijom dobijamo prosecnu vrednost dobijanog auc parametra kroz deset iteracija
cross_val_score(tree1 ,X_train, Y_train, cv = 10, scoring="roc_auc").mean()

0.5987646193261769

In [27]:
# Kada smo pravile model sa default parametrima prosecna vrednost AUC koju dobijemo kroz 10 iteracija kros validacije 
#je iznosila 0.53127953563501, a koriscenjem optimalnih parametra AUC nam se povecao na 0.5922448029073967

In [54]:
#pozivamo predikcije nad test podacima, koji predvidja koja observacija pripada kojoj klasi, 0 ili 1 
Y_pred_tree = tree1.predict(X_test)
Y_pred_tree

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
confusion_matrix(Y_test, Y_pred_tree)
#TN [0,0]
#FN [1,0]
#TP [1,1]
#FP[0,1]

#true/ predicted
#NO     NO      YES
       #TN      FP
#YES   FN      TP

#Matrica konfuzije za prvi model
#array([[1503,  285],
      # [ 206,   46]]

array([[1788,    0],
       [ 252,    0]], dtype=int64)

In [30]:
evaluate_metrics(Y_test, Y_pred_tree)
#Model ima veliku tacnost jer je pogodio sve TN klase, kojih ima znacajno vise u modelu
#Posto nije ni jednu observaciju proglasio za TP, kao ni za FN, precision, recall i f1 metrike su 0

#Accuracy : 0.759313725490196
#Precision : 0.13897280966767372
#Recall : 0.18253968253968253
#F1 : 0.15780445969125217

Accuracy : 0.8764705882352941
Precision : 0.0
Recall : 0.0
F1 : 0.0


C:\Users\zelja\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
#Ispitujemo razlicite vrednosti za hiperparametre knn modela
#n_neihbors, broj suseda na osnovu kojih ce zakljucivati o klasi
# weights, uniform- sve tacke svakog suseda su jednake tezine, distance- blizi susedi se otezavaju i imaju veci uticaj, a dalji susedi imaju manji uticaj na donosenje odluke
# metrics- koje rastojanje koristiti, Euklidsko ili Menhetn
#Menhetn rastojanje se racuna |x1-x2|+ |y1-y2| kad imamo dve osobine

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

knn_params = {'n_neighbors' : [3,5,7,9,11,13,15], 'weights' : ['uniform', 'distance'],  'metric' : ['euclidean', 'manhattan']}
knn_grid = GridSearchCV(KNeighborsClassifier(), knn_params, cv = 5, scoring="roc_auc")
knn_grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
                         'weights': ['uniform', 'distance']},
             scoring='roc_auc')

In [46]:
knn_grid.best_params_

{'metric': 'manhattan', 'n_neighbors': 15, 'weights': 'distance'}

In [48]:
#Sada pomocu dobijenih parametara pravimo novi model knn klasifikatora
knn1 = knn_grid.best_estimator_
knn1.fit(X_train, Y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=15, weights='distance')

In [56]:
cross_val_score(knn1 ,X_train, Y_train, cv = 10, scoring="roc_auc").mean()

0.6072556955802424

In [ ]:
# Kada smo pravile model sa default parametrima prosecna vrednost AUC koju dobijemo kroz 10 iteracija kros validacije 
#je iznosila 0.551016590138326, a koriscenjem optimalnih parametra AUC nam se povecao na 0.6072556955802424

In [57]:
Y_pred_knn = knn1.predict(X_test)
Y_pred_knn

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [58]:
confusion_matrix(Y_test, Y_pred_knn)
#MAtrica konfuzije prvog modela, sa default parametrima
#[1762,   26],
#[ 244,    8]

array([[1781,    7],
       [ 249,    3]], dtype=int64)

In [59]:
evaluate_metrics(Y_test, Y_pred_knn)
#Evaluacione metrike prvog modela 
#Accuracy : 0.759313725490196
#Precision : 0.13897280966767372
#Recall : 0.18253968253968253
#F1 : 0.15780445969125217

Accuracy : 0.8745098039215686
Precision : 0.3
Recall : 0.011904761904761904
F1 : 0.022900763358778622


In [63]:
#Kreirajmo VotingClassifier() sa optimalno podesenim parametrima algoritimima stabla odlucivanja i knn klasifikatora
#Kreiramo Voting model, a kao ulazne parametre mu prosledjujemo kreirane modele drvo i knn na osnovu kojih on donosi svoje zakljucke
from sklearn.ensemble import VotingClassifier

In [64]:
voting_model = VotingClassifier(voting = "soft", estimators=[('tree', tree1), ('knn', knn1)])

voting_model.fit(X_train, Y_train)

VotingClassifier(estimators=[('tree',
                              DecisionTreeClassifier(max_depth=12,
                                                     max_features=5,
                                                     min_samples_leaf=25)),
                             ('knn',
                              KNeighborsClassifier(metric='manhattan',
                                                   n_neighbors=15,
                                                   weights='distance'))],
                 voting='soft')

In [65]:
cross_val_score(voting_model, X_train, Y_train, cv=10, scoring='roc_auc').mean()
# Kod prvog modela vrednost AUC je iznosila 0.5560882027793113

0.6227119387350981

In [66]:
Y_pred_voting = voting_model.predict(X_test)
confusion_matrix(Y_test, Y_pred_voting)

#Matrica konfuzije pocetnog modela
#array([[1618,  170],
       #[ 221,   31]]

array([[1788,    0],
       [ 252,    0]], dtype=int64)

In [67]:
evaluate_metrics(Y_test, Y_pred_voting)

#Accuracy : 0.8083333333333333
#Precision : 0.15422885572139303
#Recall : 0.12301587301587301
#F1 : 0.13686534216335539

Accuracy : 0.8764705882352941
Precision : 0.0
Recall : 0.0
F1 : 0.0


C:\Users\zelja\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [68]:
#Kreirajmo BaggingClassifier(), gde cemo kao base_estimator staviti optimalno podeseni knn model:
from sklearn.ensemble import BaggingClassifier
model_bagging = BaggingClassifier(base_estimator = knn1, bootstrap=100)
model_bagging.fit(X_train, Y_train)

BaggingClassifier(base_estimator=KNeighborsClassifier(metric='manhattan',
                                                      n_neighbors=15,
                                                      weights='distance'),
                  bootstrap=100)

In [69]:
cross_val_score(model_bagging, X_train, Y_train, cv=10, scoring='roc_auc').mean()
# Kod prvog modela vrednost AUC je iznosila 0.5642404835737926

0.6077317382713819

In [70]:
Y_pred_bagging = model_bagging.predict(X_test)
confusion_matrix(Y_test, Y_pred_bagging)

#Matrica konfuzije prvog modela 
#array([[1764,   24],
 #      [ 238,   14]]

array([[1783,    5],
       [ 248,    4]], dtype=int64)

In [71]:
evaluate_metrics(Y_test, Y_pred_bagging)

#Accuracy : 0.8715686274509804
#Precision : 0.3684210526315789
#Recall : 0.05555555555555555
#F1 : 0.09655172413793105

Accuracy : 0.8759803921568627
Precision : 0.4444444444444444
Recall : 0.015873015873015872
F1 : 0.03065134099616858


# Selekcija bitnih atributa 
- Pokusacemo da odredimo K najboljih atributa koje treba izabrati za kreiranje modela, a koji su u zavisnosti sa izlaznom varijablom
- Parametar K cemo izabrati po nasoj zelji, pa npr pravicemo nove modele, a na osnovu odabira 23 atributa

In [73]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest

In [76]:
X = X.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)

In [78]:
best_features = SelectKBest(k=23, score_func = f_classif)
best_features.fit(X, Y)
#Pomocu get support uzimamo indekse kolona koje su True, bitne za nas model
best_features.get_support()

array([ True,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False, False, False,  True, False, False,  True,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False,  True, False,  True, False, False,
       False,  True,  True, False, False, False, False, False,  True,
        True, False])

In [79]:
#Sada cemo na osnovu True vrednosti napraviti novi dataset sa odabranim atributima
#Uzimamo sve redove, i samo odgovarajuce kolone
X_new = X.loc[:, best_features.get_support()]

In [80]:
X_new.head(10)

VehicleAge    VehOdo  VehBCost  WarrantyCost  AcquisitionAuctionRatio  \
0   -0.106505  0.157568 -1.065435      0.194455                -2.234466   
1    0.475038 -0.401661 -1.523737     -1.075463                -1.699265   
2   -0.106505 -0.145604 -1.581025     -0.422936                -0.680499   
3    0.475038  0.652406 -0.664420     -1.135696                -0.365471   
4    0.475038  0.319123  1.168791     -0.590250                -0.350520   
5   -0.688048 -2.437894 -0.492556     -1.356551                 0.555759   
6   -0.106505  0.066890 -1.237298     -1.177525                -0.792041   
7    0.475038  0.577501  0.538625      0.194455                -0.674444   
8    0.475038  1.038062  1.913533     -0.702351                -0.801313   
9    1.056581  0.172522  1.970821     -0.590250                 0.011925   

   AcquisitionRetailRatio  CurrentAuctionRatio  CurrentRetailRatio  \
0               -0.625095            -1.407804           -0.679097   
1               -0.670383            -1.860623           -1.232409   
2                0.648377            -1.182456           -0.080270   
3               -1.379759            -0.136272            0.122553   
4               -0.373017            -0.241899            0.597293   
5                1.206192             0.672741            0.249500   
6               -0.899194             0.143282           -0.582528   
7               -0.091268             1.367437            1.874114   
8               -0.995639            -0.737769           -0.943362   
9                0.410303             0.789847            0.598396   

   Make_CHEVROLET  Make_FORD  Make_INFINITI  Make_LEXUS  Make_MINI  \
0             0.0        0.0            0.0         0.0        0.0   
1             0.0        0.0            0.0         0.0        0.0   
2             0.0        1.0            0.0         0.0        0.0   
3             0.0        0.0            0.0         0.0        0.0   
4             0.0        0.0            0.0         0.0        0.0   
5             0.0        0.0            0.0         0.0        0.0   
6             0.0        0.0            0.0         0.0        0.0   
7             0.0        0.0            0.0         0.0        0.0   
8             0.0        1.0            0.0         0.0        0.0   
9             0.0        0.0            0.0         0.0        0.0   

   Color_GOLD  Color_OTHER  WheelType_Alloy  WheelType_Covers  Size_COMPACT  \
0         0.0          0.0              0.0               1.0           0.0   
1         0.0          0.0              1.0               0.0           1.0   
2         0.0          0.0              0.0               1.0           1.0   
3         0.0          0.0              0.0               1.0           0.0   
4         0.0          0.0              1.0               0.0           0.0   
5         1.0          0.0              0.0               1.0           0.0   
6         0.0          0.0              1.0               0.0           0.0   
7         0.0          0.0              0.0               1.0           0.0   
8         0.0          0.0              1.0               0.0           0.0   
9         0.0          0.0              1.0               0.0           0.0   

   Size_LARGE  Size_MEDIUM SUV  Size_SMALL SUV  TopThreeAmericanName_FORD  \
0         0.0              0.0             0.0                        0.0   
1         0.0              0.0             0.0                        0.0   
2         0.0              0.0             0.0                        1.0   
3         0.0              0.0             0.0                        0.0   
4         0.0              0.0             0.0                        0.0   
5         0.0              0.0             0.0                        0.0   
6         0.0              0.0             0.0                        0.0   
7         0.0              1.0             0.0                        0.0   
8         0.0              0.0             0.0               

In [81]:
#Sada na osnovu novog dataseta pravimo nove podele train i test seta
X_new_train, X_new_test, Y_new_train, Y_new_test = train_test_split(X_new, Y, test_size=0.3, random_state=0)

# Konacni modeli

In [86]:
#Drvo odlucivanja sa optimalnim parametrima i nad novim skupom podataka
tree_params = {'max_features': [3,4,5,7,10,15,17,20,23,26,30], 'min_samples_leaf': [10,15,18,20,25,28,30], 'max_depth': [10,12,15,17,20]}
tree_grid = GridSearchCV(DecisionTreeClassifier(), parameters, cv = 5, scoring='roc_auc')

tree_grid.fit(X_new_train, Y_new_train)
tree_grid.best_params_
tree2 = tree_grid.best_estimator_
tree2.fit(X_new_train, Y_new_train)

DecisionTreeClassifier(max_depth=15, max_features=3, min_samples_leaf=30)

In [87]:
cross_val_score(tree2 ,X_new_train, Y_new_train, cv = 10, scoring="roc_auc").mean()

0.5969727457104224

In [88]:
Y_pred_tree2 = tree2.predict(X_new_test)
Y_pred_tree2

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [89]:
confusion_matrix(Y_new_test, Y_pred_tree2)

array([[1777,   11],
       [ 247,    5]], dtype=int64)

In [90]:
evaluate_metrics(Y_new_test, Y_pred_tree2)

Accuracy : 0.8735294117647059
Precision : 0.3125
Recall : 0.01984126984126984
F1 : 0.03731343283582089


In [ ]:
#Knn model nad novim datasetom i sa optimalnim parametrima

In [96]:
knn_params = {'n_neighbors' : [3,5,7,9,11,13,15], 'weights' : ['uniform', 'distance'],  'metric' : ['euclidean', 'manhattan']}
knn_grid = GridSearchCV(KNeighborsClassifier(), knn_params, cv = 5, scoring="roc_auc")
knn_grid.fit(X_new_train, Y_new_train)
knn_grid.best_params_
knn2 = knn_grid.best_estimator_
knn2.fit(X_new_train, Y_new_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=15)

In [97]:
cross_val_score(knn2 ,X_new_train, Y_new_train, cv = 10, scoring="roc_auc").mean()

0.6165521901060814

In [98]:
Y_pred_knn2 = knn2.predict(X_new_test)
Y_pred_knn2

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [100]:
confusion_matrix(Y_new_test, Y_pred_knn2)

array([[1786,    2],
       [ 251,    1]], dtype=int64)

In [101]:
evaluate_metrics(Y_new_test, Y_pred_knn2)

Accuracy : 0.8759803921568627
Precision : 0.3333333333333333
Recall : 0.003968253968253968
F1 : 0.00784313725490196


In [ ]:
#Voting model nad novim datasetom i optimalnim parametrima

In [104]:
voting_model2 = VotingClassifier(voting = "soft", estimators=[('tree', tree2), ('knn', knn2)])

voting_model2.fit(X_new_train, Y_new_train)

VotingClassifier(estimators=[('tree',
                              DecisionTreeClassifier(max_depth=15,
                                                     max_features=3,
                                                     min_samples_leaf=30)),
                             ('knn',
                              KNeighborsClassifier(metric='euclidean',
                                                   n_neighbors=15))],
                 voting='soft')

In [105]:
cross_val_score(voting_model2, X_new_train, Y_new_train, cv=10, scoring='roc_auc').mean()

0.6414620805126714

In [107]:
Y_pred_voting2 = voting_model2.predict(X_new_test)
confusion_matrix(Y_new_test, Y_pred_voting2)

array([[1788,    0],
       [ 252,    0]], dtype=int64)

In [108]:
evaluate_metrics(Y_new_test, Y_pred_voting2)

Accuracy : 0.8764705882352941
Precision : 0.0
Recall : 0.0
F1 : 0.0


C:\Users\zelja\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [109]:
#Kreiramo Bagging model nad novim datasetom i optimalnim parametrima
model_bagging2 = BaggingClassifier(base_estimator = knn2, bootstrap=100)
model_bagging2.fit(X_new_train, Y_new_train)

BaggingClassifier(base_estimator=KNeighborsClassifier(metric='euclidean',
                                                      n_neighbors=15),
                  bootstrap=100)

In [110]:
cross_val_score(model_bagging2, X_new_train, Y_new_train, cv=10, scoring='roc_auc').mean()

0.6210331179022146

In [112]:
Y_pred_bagging2 = model_bagging2.predict(X_new_test)
confusion_matrix(Y_new_test, Y_pred_bagging2)

array([[1788,    0],
       [ 250,    2]], dtype=int64)

In [113]:
evaluate_metrics(Y_new_test, Y_pred_bagging2)

Accuracy : 0.8774509803921569
Precision : 1.0
Recall : 0.007936507936507936
F1 : 0.015748031496062992
